const mongoose = require("mongoose");

const contentBlockSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ["text", "image", "link", "affiliate"],
    default: "text"
  },
  value: String,
  meta: Object
}, { _id: false });

const affiliateSchema = new mongoose.Schema({
  title: String,
  link: String,
  buttonText: String,
  productImage: String,
  price: String,
  clicks: { type: Number, default: 0 },
  isAutoInjected: { type: Boolean, default: false }
}, { _id: false });

const newsSchema = new mongoose.Schema({

  category: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Category",
    required: true
  },

  title: {
    type: String,
    required: true,
    index: true
  },

  slug: {
    type: String,
    unique: true,
    index: true
  },

  subtitle: String,

  description: {
    type: String,
    required: true
  },

  contentBlocks: [contentBlockSchema],

  featuredImage: {
    public_id: String,
    url: String
  },

  affiliateLinks: [affiliateSchema],

  sourceLinks: [String], // auto fetched references

  externalLink: String,
  adsLink: String,

  // 🔥 HOMEPAGE CONTROL
  isMainTrending: {
    type: Boolean,
    default: false
  },

  isSubTrending: {
    type: Boolean,
    default: false
  },

  homeOrder: {
    type: Number,
    default: 0
  },

  // 🔥 CATEGORY CONTROL
  isCategoryTrending: {
    type: Boolean,
    default: false
  },

  isCategorySubTrending: {
    type: Boolean,
    default: false
  },

// 🔗 INTERNAL LINKING (SEO BOOST)
internalLinks: [
  {
    news: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "News"
    },
    anchorText: String, // SEO keyword
    isAutoLinked: {
      type: Boolean,
      default: true
    }
  }
],

relatedNews: [
  {
    type: mongoose.Schema.Types.ObjectId,
    ref: "News"
  }
],


// 🤖 AUTO SEO IMPROVER
seoAutoGenerated: {
  type: Boolean,
  default: true
},

seoScore: {
  type: Number,
  default: 0 // 0–100
},

seoSuggestions: [
  {
    field: String, // title, description, content
    suggestion: String,
    applied: {
      type: Boolean,
      default: false
    }
  }
],

seoLastOptimizedAt: Date,




  // 📊 ANALYTICS
  views: { type: Number, default: 0 },
  clicks: { type: Number, default: 0 },

  // 🤖 AI CONTROL
  aiGenerated: {
    type: Boolean,
    default: false
  },

  autoUpdateEnabled: {
    type: Boolean,
    default: true
  },

  lastAutoUpdatedAt: Date,

  // 🧠 SEO
  seoTitle: String,
  seoDescription: String,
  seoKeywords: [String],

  // 🧑 AUTHOR
  createdBy: {
    type: String,
    enum: ["admin", "ai"],
    default: "ai"
  },

  status: {
    type: String,
    enum: ["draft", "published", "archived"],
    default: "published"
  }

}, { timestamps: true });

module.exports = mongoose.model("News", newsSchema);
