import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getNews, updateNews, deleteNews } from "../../../api/news.api";
import { getCategories } from "../../../api/category.api";
import "./News.css"; // existing styling for news pages

const AutoNewsManager = () => {
  const [newsList, setNewsList] = useState([]);
  const [categories, setCategories] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState("");
  const navigate = useNavigate();

  // Load categories and AI news
  useEffect(() => {
    fetchCategories();
    fetchNews();
  }, []);

  const fetchCategories = async () => {
    try {
      const res = await getCategories();
      setCategories(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  const fetchNews = async () => {
    try {
      const res = await getNews();
      // Filter only AI/autogenerated news
      setNewsList(res.data.filter((n) => n.aiGenerated));
    } catch (err) {
      console.error(err);
    }
  };

  // Filter by category
  const handleCategoryFilter = (e) => {
    setSelectedCategory(e.target.value);
  };

  // Delete news
  const handleDelete = async (id) => {
    if (window.confirm("Delete this news?")) {
      await deleteNews(id);
      fetchNews();
    }
  };

  return (
    <div className="auto-news-manager">
      <h2>Autogenerated News Manager</h2>

      <div className="filter-section">
        <label>Filter by Category:</label>
        <select value={selectedCategory} onChange={handleCategoryFilter}>
          <option value="">All Categories</option>
          {categories.map((c) => (
            <option key={c._id} value={c._id}>
              {c.name} | Limit: {c.dailyAutoUpdateLimit} | AutoUpdate:{" "}
              {c.autoUpdateEnabled ? "Yes" : "No"}
            </option>
          ))}
        </select>
      </div>

      <table className="news-table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Category</th>
            <th>AI Generated</th>
            <th>Auto Update</th>
            <th>Affiliate Links</th>
            <th>SEO Score</th>
            <th>Last Auto Update</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {newsList
            .filter(
              (n) => !selectedCategory || n.category._id === selectedCategory
            )
            .map((news) => (
              <tr key={news._id}>
                <td>{news.title}</td>
                <td>{news.category?.name}</td>
                <td>{news.aiGenerated ? "Yes" : "No"}</td>
                <td>{news.autoUpdateEnabled ? "Yes" : "No"}</td>
                <td>{news.affiliateLinks?.length || 0}</td>
                <td>{news.seoScore}</td>
                <td>
                  {news.lastAutoUpdatedAt
                    ? new Date(news.lastAutoUpdatedAt).toLocaleString()
                    : "-"}
                </td>
                <td>
                  <button
                    onClick={() =>
                      navigate(`/admin/news/edit/${news.slug}`)
                    }
                  >
                    Edit
                  </button>
                  <button onClick={() => handleDelete(news._id)}>
                    Delete
                  </button>
                </td>
              </tr>
            ))}
        </tbody>
      </table>
    </div>
  );
};

export default AutoNewsManager;
